# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
# trigger:
# - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: CI
    jobs:
      - job: install_terraform_validate
        continueOnError: false
        steps:

          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '0.13.2'

          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'connect-spn-2'
              backendAzureRmResourceGroupName: 'sample-terraform-rg'
              backendAzureRmStorageAccountName: 'sampleterraform'
              backendAzureRmContainerName: 'terrform'
              backendAzureRmKey: 'development.terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: 'validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)'

  - stage: CD
    jobs:
      - deployment: deploy_terraform
        continueOnError: false
        environment : 'Development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@0
                  displayName: "install"
                  inputs:
                    terraformVersion: '0.13.2'
                - task: PowerShell@2
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Write your PowerShell commands here.
                      
                      Write-Host "Change directory"
                      cd $(System.DefaultWorkingDirectory)/terraform
                      ls
                - task: TerraformTaskV1@0
                  displayName: 'init'
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
                    backendServiceArm: 'connect-spn-2'
                    backendAzureRmResourceGroupName: 'sample-terraform-rg'
                    backendAzureRmStorageAccountName: 'sampleterraform'
                    backendAzureRmContainerName: 'terrform'
                    backendAzureRmKey: 'development.terraform.tfstate'

                - task: TerraformTaskV1@0
                  displayName: 'plan'
                  inputs:
                    provider: 'azurerm'
                    command: 'plan'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
                    commandOptions: '-var image-tag="260"'
                    environmentServiceNameAzureRM: 'connect-spn-2'
                - task: TerraformTaskV1@0
                  displayName: 'apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
                    commandOptions: '-var image-tag="260"'
                    environmentServiceNameAzureRM: 'connect-spn-2'
                    
                - task: SqlAzureDacpacDeployment@1
                  displayName: 'Products table'
                  inputs:
                    azureSubscription: 'connect-spn-2'
                    AuthenticationType: 'connectionString'
                    ConnectionString: 'Server=tcp:products-db-srv.database.windows.net,1433;Initial Catalog=products;Persist Security Info=False;User ID=azureuser;Password=$(PASSWORD);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
                    deployType: 'InlineSqlTask'
                    SqlInline: |
                        USE [products]
                        GO

                        SET ANSI_NULLS ON
                        GO

                        SET QUOTED_IDENTIFIER ON
                        GO

                        DROP TABLE [dbo].[Products];
                        GO

                        CREATE TABLE [dbo].[Products] (
                            [Id]        UNIQUEIDENTIFIER NOT NULL,
                            [Name]      NVARCHAR (50)    NULL,
                            [Price]     DECIMAL (18)     NULL,
                            [Inventory] INT              NULL,
                            [ImageUrl]  NVARCHAR (MAX)   NULL
                        )
                        GO 

                        Insert into Products (Id, Name, Price, Inventory, ImageUrl )
                        values(NEWID(), 'Book', 12, 200, 'https://sampleimagestorage.blob.core.windows.net/products/azure-app-service-erd.png')

                        Insert into Products (Id, Name, Price, Inventory, ImageUrl )
                        values(NEWID(), 'Product2', 14, 240, 'https://sampleimagestorage.blob.core.windows.net/products/azure-app-service-erd.png')

                    IpDetectionMethod: 'AutoDetect'

                - task: SqlAzureDacpacDeployment@1
                  displayName: 'Order and OrderItems table'
                  inputs:
                    azureSubscription: 'connect-spn-2'
                    AuthenticationType: 'connectionString'
                    ConnectionString: 'Server=tcp:orders-db-srv.database.windows.net,1433;Initial Catalog=orders;Persist Security Info=False;User ID=azureuser;Password=$(PASSWORD);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
                    deployType: 'InlineSqlTask'
                    SqlInline: |
                      USE [orders]
                      GO
                      
                      SET ANSI_NULLS ON
                      GO
                      
                      SET QUOTED_IDENTIFIER ON
                      GO

                      #DROP TABLE [dbo].[OrderItems];
                      #GO    

                      #DROP TABLE [dbo].[Orders];
                      #GO
                      
                      CREATE TABLE [dbo].[Orders] (
                          [Id]        UNIQUEIDENTIFIER NOT NULL,
                          [Fullname]  NVARCHAR (100)   NULL,
                          [OrderDate] SMALLDATETIME    NULL,
                          PRIMARY KEY CLUSTERED ([Id] ASC)
                      )
                      GO                        
                      
                      CREATE TABLE [dbo].[OrderItems](
                          [Id] INT NOT NULL PRIMARY KEY, 
                          [OrderId] UNIQUEIDENTIFIER NULL, 
                          [Name] NVARCHAR(50) NULL, 
                          [Price] DECIMAL NULL, 
                          [Quantity] INT NULL, 
                          CONSTRAINT [FK_OrderOrderItem] FOREIGN KEY ([OrderId]) REFERENCES [Orders]([Id])
                      )
                      GO
                    IpDetectionMethod: 'AutoDetect'
