version: '3.4'

services:
  sample.api.products:
    image: ${DOCKER_REGISTRY-}sampleapiproducts
    build:
      context: .
      dockerfile: Sample.Api.Products\Dockerfile

  sample.api.images:
    image: ${DOCKER_REGISTRY-}sampleapiimages
    build:
      context: .
      dockerfile: Sample.Api.Images\Dockerfile

  sample.api.orders:
    image: ${DOCKER_REGISTRY-}sampleapiorders
    build:
      context: .
      dockerfile: Sample.Api.Orders\Dockerfile

